server:
  port: 8085
spring:
  profiles:
    active: dev
  application:
    name: life_cycle
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "***"
    username: "***"
    password: "***"
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段


mybatis-plus:
  type-aliases-package: com.cc.entity # 别名扫描包
jwt:
  secret-key: "****"
  ttl:  86400000000000
logging:
  level:
    com.cc: debug

rocketmq:
  name-server: localhost:9876
  producer:
    group: seckill-producer-group
    send-message-timeout: 3000

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: tongyi-xiaomi-analysis-flash
      log-requests: true
      log-responses: true
    embedding-model:
      api-key: ${OPENAI_API_KEY}
      model-name: text-embedding-v1
      log-requests: true
      log-responses: true

milvus:
  uri: "http://localhost:19530"
  database: milvus_life_cycle.db
  dimension: 768
  token: "****"
